/* **************************************************************************** */
/*   Descripciones de la Base de Datos de Analitica Web                         */ 
/* **************************************************************************** */
  
  /* Tabla de Hojas Analiticas */

CREATE TABLE HOJAS (HOJA INTEGER NOT NULL,
  TITULO VARCHAR(30),
  INVISIBLE BOOLEAN,
  HOJAEXTERNA VARCHAR(5),
  TIPOHOJA VARCHAR(2),
  LINEA_RESULTADO INTEGER,
  LINEA_FACTURACION INTEGER,
  PRIMARY KEY(HOJA));
  
  /* Tabla de Lineas Analiticas */
  
CREATE TABLE LINEAS (HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  TITULO VARCHAR(30),
  REFHOJA INTEGER,
  REFLINEA INTEGER,
  INVISIBLE BOOLEAN,
  PASADA_CALCULO INTEGER,
  DE_TOTALES BOOLEAN,
  INTENSA BOOLEAN,
  BLANCA BOOLEAN,
  SUMABLE BOOLEAN,
  ESTADISTICA BOOLEAN,
  CON_DECIMALES BOOLEAN,
  CARACTER_BLANCO CHAR,
  NO_ACUMULABLE BOOLEAN,
  CON_PORCENTAJE BOOLEAN,
  REDUCCION_A_MILLARES BOOLEAN,
  LINEA_DE_MARGEN BOOLEAN,
  LINEA_DE_REPARTO BOOLEAN,
  TIPO_ACUMULADO INTEGER,
  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla de Tipos de Hoja Ana */
  
CREATE TABLE TIPOS_HOJAS(TIPO VARCHAR(2) NOT NULL,
  TITULO VARCHAR(30),
  PRIMARY KEY(TIPO));
  
  /* Tabla de Fichero de Parametros (ULTIMO) */
  
CREATE TABLE PARAMETROS_APP(UNO INTEGER NOT NULL,
  TITULO_EMPRESA VARCHAR(40),
  ESCUDO_EMPRESA VARCHAR(80),
  MAX_PASADAS INTEGER,
  MES_EN_CURSO INTEGER,
  ANNO_EN_CURSO INTEGER,
  TITULO_CORTO_EMPRESA VARCHAR(20),
  ANNO_PRESUPUESTO INTEGER,
  FECHA_PPTO DATE,
  HORA_PPTO VARCHAR(15),
  OBLIG_DESC_ADICIONAL BOOLEAN,
  PRESUPUESTO_ACTIVO BOOLEAN,
  ADMITE_SUBCTA_VACIA BOOLEAN,
  CARGOS_A_NO_VISIBLE BOOLEAN,
  CONTROL_FECHA_MOVIM BOOLEAN,
  HOJA_RESULTADO INTEGER,
  LINEA_RESULTADO INTEGER,
  HOJA_FACTURACION INTEGER,
  LINEA_FACTURACION INTEGER,
  PRIMARY KEY(UNO));
 
  /* Tabla de Fichero de Configuracion */
  
CREATE TABLE CONFIGURACION_APP(UNO INTEGER NOT NULL,
  ESCUDO_PORTADA VARCHAR(80),
  ANCHO_ESCUDO_PORTADA INTEGER,
  ALTO_ESCUDO_PORTADA INTEGER,
  ESCUDO_PANTALLA VARCHAR(80),
  ANCHO_ESCUDO_PANTALLA INTEGER,
  ALTO_ESCUDO_PANTALLA INTEGER,
  PRIMARY KEY(UNO));

  /* Tabla Indicadores */
  
CREATE TABLE INDICADORES(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  ENCENDIDO BOOLEAN,
  PRIMARY KEY(INDICE));
  
  /* Tabla de cifras analiticas */
  
CREATE TABLE CIFRAS(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  MESM24 NUMERIC(15,2),
  MESM23 NUMERIC(15,2),
  MESM22 NUMERIC(15,2),
  MESM21 NUMERIC(15,2),
  MESM20 NUMERIC(15,2),
  MESM19 NUMERIC(15,2),
  MESM18 NUMERIC(15,2),
  MESM17 NUMERIC(15,2),
  MESM16 NUMERIC(15,2),
  MESM15 NUMERIC(15,2),
  MESM14 NUMERIC(15,2),
  MESM13 NUMERIC(15,2),
  MESM12 NUMERIC(15,2),
  MESM11 NUMERIC(15,2),
  MESM10 NUMERIC(15,2),
  MESM09 NUMERIC(15,2),
  MESM08 NUMERIC(15,2),
  MESM07 NUMERIC(15,2),
  MESM06 NUMERIC(15,2),
  MESM05 NUMERIC(15,2),
  MESM04 NUMERIC(15,2),
  MESM03 NUMERIC(15,2),
  MESM02 NUMERIC(15,2),
  MESM01 NUMERIC(15,2),
  MESCALCULO NUMERIC(15,2),
  CERRADA BOOLEAN,
  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla de Cifras Extras */
  
CREATE TABLE CIFRAS_EXT(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  MESM24 NUMERIC(15,2),
  MESM23 NUMERIC(15,2),
  MESM22 NUMERIC(15,2),
  MESM21 NUMERIC(15,2),
  MESM20 NUMERIC(15,2),
  MESM19 NUMERIC(15,2),
  MESM18 NUMERIC(15,2),
  MESM17 NUMERIC(15,2),
  MESM16 NUMERIC(15,2),
  MESM15 NUMERIC(15,2),
  MESM14 NUMERIC(15,2),
  MESM13 NUMERIC(15,2),
  MESM12 NUMERIC(15,2),
  MESM11 NUMERIC(15,2),
  MESM10 NUMERIC(15,2),
  MESM09 NUMERIC(15,2),
  MESM08 NUMERIC(15,2),
  MESM07 NUMERIC(15,2),
  MESM06 NUMERIC(15,2),
  MESM05 NUMERIC(15,2),
  MESM04 NUMERIC(15,2),
  MESM03 NUMERIC(15,2),
  MESM02 NUMERIC(15,2),
  MESM01 NUMERIC(15,2),
  MESCALCULO NUMERIC(15,2),
  CERRADA BOOLEAN,
  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla de Presupuesto */
  
CREATE TABLE PRESUPUESTO(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  MES01 NUMERIC(15,2),
  MES02 NUMERIC(15,2),
  MES03 NUMERIC(15,2),
  MES04 NUMERIC(15,2),
  MES05 NUMERIC(15,2),
  MES06 NUMERIC(15,2),
  MES07 NUMERIC(15,2),
  MES08 NUMERIC(15,2),
  MES09 NUMERIC(15,2),
  MES10 NUMERIC(15,2),
  MES11 NUMERIC(15,2),
  MES12 NUMERIC(15,2),
  ACUMULADO NUMERIC(15,2),
  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla Historico de Presupuesto */
  
CREATE TABLE HISTO_PRESUPUESTO(ANNO INTEGER NOT NULL,
  HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  MES01 NUMERIC(15,2),
  MES02 NUMERIC(15,2),
  MES03 NUMERIC(15,2),
  MES04 NUMERIC(15,2),
  MES05 NUMERIC(15,2),
  MES06 NUMERIC(15,2),
  MES07 NUMERIC(15,2),
  MES08 NUMERIC(15,2),
  MES09 NUMERIC(15,2),
  MES10 NUMERIC(15,2),
  MES11 NUMERIC(15,2),
  MES12 NUMERIC(15,2),
  ACUMULADO NUMERIC(15,2),
  PRIMARY KEY(ANNO,HOJA,LINEA));
       
  /* Tabla de Valores del Presupuesto */
  
CREATE TABLE VALORES_PPTO(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  PRESUPUESTO NUMERIC(15,2),
  GRABADA BOOLEAN,
  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla Repartos del presupuesto LINEAS */
  
CREATE TABLE REPARTO_PPTO_LINEAS(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  REP_MES01 NUMERIC(14,5),
  REP_MES02 NUMERIC(14,5),
  REP_MES03 NUMERIC(14,5),
  REP_MES04 NUMERIC(14,5),
  REP_MES05 NUMERIC(14,5),
  REP_MES06 NUMERIC(14,5),
  REP_MES07 NUMERIC(14,5),
  REP_MES08 NUMERIC(14,5),
  REP_MES09 NUMERIC(14,5),
  REP_MES10 NUMERIC(14,5),
  REP_MES11 NUMERIC(14,5),
  REP_MES12 NUMERIC(14,5),
  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla Repartos del presupuesto HOJAS */
  
CREATE TABLE REPARTO_PPTO_HOJAS(HOJA INTEGER NOT NULL,
  REP_MES01 NUMERIC(14,5),
  REP_MES02 NUMERIC(14,5),
  REP_MES03 NUMERIC(14,5),
  REP_MES04 NUMERIC(14,5),
  REP_MES05 NUMERIC(14,5),
  REP_MES06 NUMERIC(14,5),
  REP_MES07 NUMERIC(14,5),
  REP_MES08 NUMERIC(14,5),
  REP_MES09 NUMERIC(14,5),
  REP_MES10 NUMERIC(14,5),
  REP_MES11 NUMERIC(14,5),
  REP_MES12 NUMERIC(14,5),
  PRIMARY KEY(HOJA));
  
  /* Tabla Repartos del presupuesto GLOBAL */
  
CREATE TABLE REPARTO_PPTO_GLOBAL(UNO INTEGER NOT NULL,
  REP_MES01 NUMERIC(14,5),
  REP_MES02 NUMERIC(14,5),
  REP_MES03 NUMERIC(14,5),
  REP_MES04 NUMERIC(14,5),
  REP_MES05 NUMERIC(14,5),
  REP_MES06 NUMERIC(14,5),
  REP_MES07 NUMERIC(14,5),
  REP_MES08 NUMERIC(14,5),
  REP_MES09 NUMERIC(14,5),
  REP_MES10 NUMERIC(14,5),
  REP_MES11 NUMERIC(14,5),
  REP_MES12 NUMERIC(14,5),
  PRIMARY KEY(UNO));
  
  /* Tabla Notas al presupuesto */
  
CREATE TABLE NOTAS_PPTO(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  NOTA VARCHAR(30),
  PRIMARY KEY(HOJA,LINEA));
  
 /* Tabla de Asignaciones de Cuentas */
 
CREATE TABLE TABLA_ASIGNACIONES(CUENTA VARCHAR(20) NOT NULL,
  SUBCUENTA VARCHAR(10) NOT NULL,
  TITULO VARCHAR(30),
  HOJA INTEGER,
  LINEA INTEGER,
  MODELO VARCHAR(2),
  PRIMARY KEY(CUENTA,SUBCUENTA));
  
  /* Tabla de Movimientos Contables */
  
CREATE TABLE MOVIMIENTOS(HOJA integer not null,
  LINEA integer not null,
  ANNO integer not null,
  MES integer not null,
  SECUENCIA integer not null,
  DESCRIPCION varchar(70),
  IMPORTE numeric(15,2),
  SIGNO varchar(1),
  REFERENCIA varchar(10),
  CUENTA varchar(20),
  SUBCUENTA varchar(10),
  FECHA date,
  ORIGEN VARCHAR(2),
  primary key (HOJA,LINEA,ANNO,MES,SECUENCIA));
   
  /* Tabla Historico de Cifras */
  
CREATE TABLE HISTO_CIFRAS(ANNO INTEGER NOT NULL,
  HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  MES01 NUMERIC(15,2),
  MES02 NUMERIC(15,2),
  MES03 NUMERIC(15,2),
  MES04 NUMERIC(15,2),
  MES05 NUMERIC(15,2),
  MES06 NUMERIC(15,2),
  MES07 NUMERIC(15,2),
  MES08 NUMERIC(15,2),
  MES09 NUMERIC(15,2),
  MES10 NUMERIC(15,2),
  MES11 NUMERIC(15,2),
  MES12 NUMERIC(15,2),
  PRIMARY KEY(ANNO,HOJA,LINEA));
    
  /* Tabla Historico de Cifras Extras */
  
CREATE TABLE HISTO_CIFRAS_EXTRAS(ANNO INTEGER NOT NULL,
  HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  MES01 NUMERIC(15,2),
  MES02 NUMERIC(15,2),
  MES03 NUMERIC(15,2),
  MES04 NUMERIC(15,2),
  MES05 NUMERIC(15,2),
  MES06 NUMERIC(15,2),
  MES07 NUMERIC(15,2),
  MES08 NUMERIC(15,2),
  MES09 NUMERIC(15,2),
  MES10 NUMERIC(15,2),
  MES11 NUMERIC(15,2),
  MES12 NUMERIC(15,2),
  PRIMARY KEY(ANNO,HOJA,LINEA));
  
  /* Tabla de Totales */
  
CREATE TABLE TOTALES(HOJA INTEGER NOT NULL,
  LINEA INTEGER NOT NULL,
  NUM_COMPONENTES INTEGER,
  
  COEF01 NUMERIC(15,4),
  HOJA01 INTEGER,
  LINEA01 INTEGER,
  MAS01 VARCHAR(1),
  
  COEF02 NUMERIC(15,4),
  HOJA02 INTEGER,
  LINEA02 INTEGER,
  MAS02 VARCHAR(1),
  
  COEF03 NUMERIC(15,4),
  HOJA03 INTEGER,
  LINEA03 INTEGER,
  MAS03 VARCHAR(1),
  
  COEF04 NUMERIC(15,4),
  HOJA04 INTEGER,
  LINEA04 INTEGER,
  MAS04 VARCHAR(1),
  
  COEF05 NUMERIC(15,4),
  HOJA05 INTEGER,
  LINEA05 INTEGER,
  MAS05 VARCHAR(1),
  
  COEF06 NUMERIC(15,4),
  HOJA06 INTEGER,
  LINEA06 INTEGER,
  MAS06 VARCHAR(1),
  
  COEF07 NUMERIC(15,4),
  HOJA07 INTEGER,
  LINEA07 INTEGER,
  MAS07 VARCHAR(1),
  
  COEF08 NUMERIC(15,4),
  HOJA08 INTEGER,
  LINEA08 INTEGER,
  MAS08 VARCHAR(1),
  
  COEF09 NUMERIC(15,4),
  HOJA09 INTEGER,
  LINEA09 INTEGER,
  MAS09 VARCHAR(1),
  
  COEF10 NUMERIC(15,4),
  HOJA10 INTEGER,
  LINEA10 INTEGER,
  MAS10 VARCHAR(1),
  
  COEF11 NUMERIC(15,4),
  HOJA11 INTEGER,
  LINEA11 INTEGER,
  MAS11 VARCHAR(1),
  
  COEF12 NUMERIC(15,4),
  HOJA12 INTEGER,
  LINEA12 INTEGER,
  MAS12 VARCHAR(1),
  
  COEF13 NUMERIC(15,4),
  HOJA13 INTEGER,
  LINEA13 INTEGER,
  MAS13 VARCHAR(1),
  
  COEF14 NUMERIC(15,4),
  HOJA14 INTEGER,
  LINEA14 INTEGER,
  MAS14 VARCHAR(1),
  
  COEF15 NUMERIC(15,4),
  HOJA15 INTEGER,
  LINEA15 INTEGER,
  MAS15 VARCHAR(1),
  
  COEF16 NUMERIC(15,4),
  HOJA16 INTEGER,
  LINEA16 INTEGER,
  MAS16 VARCHAR(1),
  
  COEF17 NUMERIC(15,4),
  HOJA17 INTEGER,
  LINEA17 INTEGER,
  MAS17 VARCHAR(1),
  
  COEF18 NUMERIC(15,4),
  HOJA18 INTEGER,
  LINEA18 INTEGER,
  MAS18 VARCHAR(1),
  
  COEF19 NUMERIC(15,4),
  HOJA19 INTEGER,
  LINEA19 INTEGER,
  MAS19 VARCHAR(1),
  
  COEF20 NUMERIC(15,4),
  HOJA20 INTEGER,
  LINEA20 INTEGER,
  MAS20 VARCHAR(1),
  
  COEF21 NUMERIC(15,4),
  HOJA21 INTEGER,
  LINEA21 INTEGER,
  MAS21 VARCHAR(1),
  
  COEF22 NUMERIC(15,4),
  HOJA22 INTEGER,
  LINEA22 INTEGER,
  MAS22 VARCHAR(1),
  
  COEF23 NUMERIC(15,4),
  HOJA23 INTEGER,
  LINEA23 INTEGER,
  MAS23 VARCHAR(1),
  
  COEF24 NUMERIC(15,4),
  HOJA24 INTEGER,
  LINEA24 INTEGER,
  MAS24 VARCHAR(1),
  
  COEF25 NUMERIC(15,4),
  HOJA25 INTEGER,
  LINEA25 INTEGER,
  MAS25 VARCHAR(1),
  
  COEF26 NUMERIC(15,4),
  HOJA26 INTEGER,
  LINEA26 INTEGER,
  MAS26 VARCHAR(1),
  
  COEF27 NUMERIC(15,4),
  HOJA27 INTEGER,
  LINEA27 INTEGER,
  MAS27 VARCHAR(1),
  
  COEF28 NUMERIC(15,4),
  HOJA28 INTEGER,
  LINEA28 INTEGER,
  MAS28 VARCHAR(1),
  
  COEF29 NUMERIC(15,4),
  HOJA29 INTEGER,
  LINEA29 INTEGER,
  MAS29 VARCHAR(1),
  
  COEF30 NUMERIC(15,4),
  HOJA30 INTEGER,
  LINEA30 INTEGER,
  MAS30 VARCHAR(1),
  
  COEF31 NUMERIC(15,4),
  HOJA31 INTEGER,
  LINEA31 INTEGER,
  MAS31 VARCHAR(1),
  
  COEF32 NUMERIC(15,4),
  HOJA32 INTEGER,
  LINEA32 INTEGER,
  MAS32 VARCHAR(1),
  
  COEF33 NUMERIC(15,4),
  HOJA33 INTEGER,
  LINEA33 INTEGER,
  MAS33 VARCHAR(1),
  
  COEF34 NUMERIC(15,4),
  HOJA34 INTEGER,
  LINEA34 INTEGER,
  MAS34 VARCHAR(1),
  
  COEF35 NUMERIC(15,4),
  HOJA35 INTEGER,
  LINEA35 INTEGER,
  MAS35 VARCHAR(1),
  
  COEF36 NUMERIC(15,4),
  HOJA36 INTEGER,
  LINEA36 INTEGER,
  MAS36 VARCHAR(1),
  
  COEF37 NUMERIC(15,4),
  HOJA37 INTEGER,
  LINEA37 INTEGER,
  MAS37 VARCHAR(1),
  
  COEF38 NUMERIC(15,4),
  HOJA38 INTEGER,
  LINEA38 INTEGER,
  MAS38 VARCHAR(1),
  
  COEF39 NUMERIC(15,4),
  HOJA39 INTEGER,
  LINEA39 INTEGER,
  MAS39 VARCHAR(1),
  
  COEF40 NUMERIC(15,4),
  HOJA40 INTEGER,
  LINEA40 INTEGER,
  MAS40 VARCHAR(1),
  
  COEF41 NUMERIC(15,4),
  HOJA41 INTEGER,
  LINEA41 INTEGER,
  MAS41 VARCHAR(1),
  
  COEF42 NUMERIC(15,4),
  HOJA42 INTEGER,
  LINEA42 INTEGER,
  MAS42 VARCHAR(1),
  
  COEF43 NUMERIC(15,4),
  HOJA43 INTEGER,
  LINEA43 INTEGER,
  MAS43 VARCHAR(1),
  
  COEF44 NUMERIC(15,4),
  HOJA44 INTEGER,
  LINEA44 INTEGER,
  MAS44 VARCHAR(1),
  
  COEF45 NUMERIC(15,4),
  HOJA45 INTEGER,
  LINEA45 INTEGER,
  MAS45 VARCHAR(1),

  PRIMARY KEY(HOJA,LINEA));
  
  /* Tabla Mascaras de Cuentas */
  
CREATE TABLE MASCARAS_CUENTAS(UNO INTEGER NOT NULL,
  NUM_MASCARAS INTEGER,
  MASCARA01 VARCHAR(20),
  MASCARA02 VARCHAR(20),
  MASCARA03 VARCHAR(20),
  MASCARA04 VARCHAR(20),
  MASCARA05 VARCHAR(20),
  MASCARA06 VARCHAR(20),
  MASCARA07 VARCHAR(20),
  MASCARA08 VARCHAR(20),
  MASCARA09 VARCHAR(20),
  MASCARA10 VARCHAR(20),
  MASCARA11 VARCHAR(20),
  MASCARA12 VARCHAR(20),
  MASCARA13 VARCHAR(20),
  MASCARA14 VARCHAR(20),
  MASCARA15 VARCHAR(20),
  PRIMARY KEY(UNO));  
  
  /* Tabla de Fichero Diario */
  
CREATE TABLE DIARIO_FICHERO(ORIGEN VARCHAR(2) NOT NULL,
  SECUENCIA integer not null,
  CUENTA varchar(20),
  SUBCUENTA varchar(10),
  FECHA date,
  REFERENCIA varchar(10),
  IMPORTE numeric(15,2),
  SIGNO varchar(1),
  DESCRIPCION varchar(70),
  primary key (ORIGEN,SECUENCIA));
   
  /* Tabla de Fichero Diario Copia */
  
CREATE TABLE DIARIO_COPIA(ORIGEN VARCHAR(2) NOT NULL,
  SECUENCIA integer not null,
  CUENTA varchar(20),
  SUBCUENTA varchar(10),
  FECHA date,
  REFERENCIA varchar(10),
  IMPORTE numeric(15,2),
  SIGNO varchar(1),
  DESCRIPCION varchar(70),
  primary key (ORIGEN,SECUENCIA));

/* Origenes de Datos Diario */

CREATE TABLE ORIGENES_DIARIO(CLAVE_ORIGEN VARCHAR(2) NOT NULL,
  TITULO VARCHAR(30),
PRIMARY KEY(CLAVE_ORIGEN));
   
  /* Tabla de Datos Adicionales Costes */
  
CREATE TABLE ADICIONALES_COSTES(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
  
  /* Tabla de Datos Adicionales Estadisticos */
  
CREATE TABLE ADICIONALES_ESTADISTICOS(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
  
  /* Tabla de Datos Adicionales Correcciones */
  
CREATE TABLE ADICIONALES_CORRECCIONES(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
  
  /* Tabla de Datos Acumulados Estadisticos */
  
CREATE TABLE ACUMULADOS_ESTADISTICOS(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
      
  /* Tabla de Datos Adicionales Costes Copia */
  
CREATE TABLE ADIC_COSTES_COPIA(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
  
  /* Tabla de Datos Adicionales Estadisticos Copia*/
  
CREATE TABLE ADIC_ESTADISTICOS_COPIA(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
  
  /* Tabla de Datos Adicionales Correcciones Copia */
  
CREATE TABLE ADIC_CORRECCIONES_COPIA(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
  
  /* Tabla de Datos Acumulados Estadisticos Copia */
  
CREATE TABLE ACUM_ESTADISTICOS_COPIA(INDICE INTEGER NOT NULL,
  TITULO VARCHAR(30),
  IMPORTE NUMERIC(15,2),
  HOJA INTEGER,
  LINEA INTEGER,
  BLANCA BOOLEAN,
  GRABADA BOOLEAN,
  ORDEN VARCHAR(10),
  PRIMARY KEY(INDICE));
      
  /* Tabla de Correciones Especiales */
  
CREATE TABLE CORRECCIONES_ESPE(INDICE INTEGER NOT NULL,
  HOJA INTEGER,
  LINEA INTEGER,
  IMPORTE NUMERIC(15,2),
  CAUSA VARCHAR(30),
  GRABADA BOOLEAN,
  PRIMARY KEY(INDICE));
  
  /* Tabla de Correciones Especiales Copia */
  
CREATE TABLE CORRECCIONES_ESPE_COPIA(INDICE INTEGER NOT NULL,
  HOJA INTEGER,
  LINEA INTEGER,
  IMPORTE NUMERIC(15,2),
  CAUSA VARCHAR(30),
  GRABADA BOOLEAN,
  PRIMARY KEY(INDICE));
